package HTTP::MobileAgent::Flash::DoCoMoFlashMap;
# -------------------------------------------------------------------------
# This file is autogenerated by makedocomomap
# in HTTP-MobileAgent-Flash distribution
# -------------------------------------------------------------------------
use strict;
use warnings;

require Exporter;
use base qw(Exporter);
use vars qw(@EXPORT_OK $FLASH_MAP);
@EXPORT_OK = qw($FLASH_MAP);


BEGIN {
	if ($ENV{DOCOMO_FLASH_MAP}) {
		eval q{
			require YAML::Syck;
			$FLASH_MAP = YAML::Syck::LoadFile($ENV{DOCOMO_FLASH_MAP});
		};
		if ($@) {
			eval q{
				require YAML;
				$FLASH_MAP = YAML::LoadFile($ENV{DOCOMO_FLASH_MAP});
			};
		}
		warn "using normal hash map: $@" if $@;
	}
}

$FLASH_MAP ||= {
  'N506IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '295'
  },
  'N900I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '269'
  },
  'N701I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'SH901IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'SO505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '256'
  },
  'D701I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'F700IS' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'N700I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'D506I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '270'
  },
  'D902I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '320'
  },
  'SH505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '200',
    'height' => '252'
  },
  'P900I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '266'
  },
  'D701IWM' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'P900IV' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '266'
  },
  'P851I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'P901I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'D901I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'F900IT' => {
    'width' => '230',
    'version' => '1.0',
    'max_file_size' => '1000',
    'height' => '240'
  },
  'D505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '200',
    'height' => '270'
  },
  'F900IC' => {
    'width' => '230',
    'version' => '1.0',
    'max_file_size' => '1000',
    'height' => '240'
  },
  'P505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '404',
    'height' => '266'
  },
  'N505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '270'
  },
  'P902I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'D901IS' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'N505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '200',
    'height' => '270'
  },
  'N506I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '295'
  },
  'D505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '270'
  },
  'SH700I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'N900IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '269'
  },
  'P701ID' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'N901IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'F902I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'P505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '256',
    'height' => '266'
  },
  'SH900I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1000',
    'height' => '252'
  },
  'SO506IC' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '256'
  },
  'F901IC' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'SO506I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '256'
  },
  'N902I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'SH902I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'F700I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'P901IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'D900I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '270'
  },
  'F900I' => {
    'width' => '230',
    'version' => '1.0',
    'max_file_size' => '1000',
    'height' => '240'
  },
  'F901IS' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'N901IC' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'F505IGPS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '268'
  },
  'N900IG' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '269'
  },
  'SO505I' => {
    'width' => '256',
    'version' => '1.0',
    'max_file_size' => '200',
    'height' => '240'
  },
  'SH506IC' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '252'
  },
  'N900IL' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '269'
  },
  'P506IC' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '404',
    'height' => '266'
  },
  'P700I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'F505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '268'
  },
  'SA700IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'SH901IC' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'SH700IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'SO506IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '256'
  },
  'SH505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '252'
  },
  'F506I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '268'
  }
}
;

1;
